# Generated by Django 3.0.5 on 2020-07-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200727_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_description',
            field=models.TextField(blank=True),
        ),
    ]
